# Generated by Django 4.0.1 on 2022-01-28 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('separator', models.CharField(choices=[(',', 'Comma (,)'), (';', 'Semi column (;)')], max_length=10)),
                ('quote', models.CharField(choices=[('"', 'Double quote (")'), ("'", "Quote (')")], max_length=10)),
                ('date', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TypeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('full_name', 'Full name'), ('age', 'Age'), ('email', 'Email'), ('phone_number', 'Phone numbers'), ('address', 'Address')], max_length=30)),
                ('From', models.IntegerField(blank=True)),
                ('to', models.IntegerField(blank=True)),
                ('order', models.IntegerField()),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='create_schemas.schema')),
            ],
        ),
    ]
